#!/usr/bin/env bash

function install {
  sudo dnf install -y $@
}

sudo cp repos/*.repo /etc/yum.repos.d/

install epel-release
install neovim git nushell tree fastfetch util-linux-user golang carapace-bin

sudo cp etc/issue /etc/issue

sudo chsh -s /usr/bin/nu $USER
